namespace Xenomech.Enumeration
{
    // Note: These IDs are tied to 2DAs. Don't reassign ID numbers unless you also update the 2DA files.
    public enum PerkType
    {
        Invalid = 0,
        Doublehand = 1,
        DualWield = 2,
        WeaponFinesse = 3,
        WeaponFocusLongswords = 4,
        ImprovedCriticalLongswords = 5,
        LongswordProficiency = 6,
        LongswordMastery = 7,
        HackingBlade = 8,
        RiotBlade = 9,
        WeaponFocusKnives = 10,
        ImprovedCriticalKnives = 11,
        KnifeProficiency = 12,
        KnifeMastery = 13,
        PoisonStab = 14,
        Backstab = 15,
        
        ThermoCube = 16,
        ElementalSpread = 17,
        AquaIce = 18,
        Clarity = 19,
        AnemoBolt = 20,
        ElementalSeal = 21,

        PowerAttack = 22,
        SuperiorWeaponFocus = 23,
        IncreasedMultiplier = 24,
        Cleave = 25,
        WeaponFocusGreatswords = 26,
        ImprovedCriticalGreatswords = 27,
        GreatswordProficiency = 28,
        GreatswordMastery = 29,
        CrescentMoon = 30,
        HardSlash = 31,
        WeaponFocusPolearms = 32,
        ImprovedCriticalPolearms = 33,
        PolearmProficiency = 34,
        PolearmMastery = 35,
        Skewer = 36,
        DoubleThrust = 37,
        WeaponFocusTwinBlades = 38,
        ImprovedCriticalTwinBlades = 39,
        TwinBladeProficiency = 40,
        TwinBladeMastery = 41,
        LegSweep = 42,
        CrossCut = 43,
        
        Sazanami = 44,
        ArcaneSpread = 45,
        Ryokusho = 46,
        Kaseii = 47,
        Senkei = 48,
        ClearMind = 49,

        Knockdown = 50,
        FlurryOfBlows = 51,
        InnerStrength = 52,
        MartialFinesse = 53,
        WeaponFocusKnuckles = 54,
        ImprovedCriticalKnuckles = 55,
        KnucklesProficiency = 56,
        KnucklesMastery = 57,
        ElectricFist = 58,
        StrikingCobra = 59,
        WeaponFocusStaves = 60,
        ImprovedCriticalStaves = 61,
        StaffProficiency = 62,
        StaffMastery = 63,
        Slam = 64,
        SpinningWhirl = 65,
        RapidShot = 66,
        RapidReload = 67,
        ZenMarksmanship = 68,
        PrecisionAim = 69,
        PointBlankShot = 70,
        WeaponFocusPistols = 71,
        ImprovedCriticalPistols = 72,
        PistolProficiency = 73,
        PistolMastery = 74,
        QuickDraw = 75,
        DoubleShot = 76,
        WeaponFocusThrowingWeapons = 77,
        ImprovedCriticalThrowingWeapons = 78,
        ThrowingWeaponProficiency = 79,
        ThrowingWeaponMastery = 80,
        ExplosiveToss = 81,
        PiercingToss = 82,
        
        ArcaneSpikes = 83,
        Convert = 84,
        LightningSpirit = 85,
        EtherFlow = 86,
        EarthSpirit = 87,
        SpiritualBonding = 88,

        WeaponFocusRifles = 89,
        ImprovedCriticalRifles = 90,
        RifleProficiency = 91,
        RifleMastery = 92,
        TranquilizerShot = 93,
        CripplingShot = 94,
        
        HolySpirit = 95,
        EtherConduit = 96,
        MechPiloting = 97,
        MechWeaponry = 98,
        MechDefenses = 99,
        FuelConservation = 100,
        ImprovedFocus = 101,

        CloakProficiency = 102,
        BeltProficiency = 103,
        RingProficiency = 104,
        NecklaceProficiency = 105,
        BreastplateProficiency = 106,
        HelmetProficiency = 107,
        BracerProficiency = 108,
        LeggingProficiency = 109,
        ShieldProficiency = 110,
        TunicProficiency = 111,
        CapProficiency = 112,
        GloveProficiency = 113,
        BootProficiency = 114,
        
        RangedHealing = 122,
        FrugalMedic = 123,
        RecoveryItems = 124,
        StimPacks = 125,
        OneHandedBlueprints = 127,
        TwoHandedBlueprints = 128,
        MartialBlueprints = 129,
        RangedBlueprints = 130,
        ArmorBlueprints = 132,
        AccessoryBlueprints = 133,
        ImplantInstallation = 140,
        
        HeadImplantBlueprints = 142,
        ArmImplantBlueprints = 143,
        LegImplantBlueprints = 144,
        FootImplantBlueprints = 145,
        BodyImplantBlueprints = 146,
        
        
        FurnitureBlueprints = 149,
        
        Harvesting = 157,
        Refining = 158,
        RefineryManagement = 159,
        Scavenging = 160,
        HardLook = 161,
        
        
        
        TreasureHunter = 1002,
        CreditFinder = 1003,
        GuildRelations = 1004,

    }
}
