namespace Xenomech.Enumeration
{
    public enum StatusEffectType
    {
        Invalid = 0,
        ElementalSeal = 1,
        Shock = 2,
        Burn = 3,
        ElementalSpread = 4,
        ArcaneSpread = 5,
        EtherPack1 = 6,
        EtherPack2 = 7,
        EtherPack3 = 8,
        EtherPack4 = 9,
        EtherPack5 = 10,
        StaminaPack1 = 11,
        StaminaPack2 = 12,
        StaminaPack3 = 13,
        StaminaPack4 = 14,
        StaminaPack5 = 15,
        Poison = 16,
        Bleed = 17,
        EtherConduit = 18,
        SpiritOfRage1 = 19,
        SpiritOfRage2 = 20,
        SpiritOfRage3 = 21,
        SpiritOfChange1 = 22,
        SpiritOfChange2 = 23,
        SpiritOfChange3 = 24,
        SpiritOfFaith1 = 25,
        SpiritOfFaith2 = 26,
        SpiritOfFaith3 = 27,
        Tranquilize = 41,
        Rest = 43,
    }
}
